### PR TITLE
Fixing the project configuration after its URL was changed

### LINKED ISSUE #13: Project clean up items for integration into Solace Dev Portal
We should update the following items to improve ease of use in this project:

- README should clearly mention the QPID JMS API in the initial summary and project heading.
- Contributing.md needs link cleanup now that project is moved.
- README quick links to tutorials need a link update to reflect final project naming.
- Contributors link in README needs a link update
- NOTICE should be updated to only list 2017.
- config.yml needs a small update to reflect final project naming.
- Tutorials.yml needs a small update to include QPID in the title.
- All tutorials md files should mention QPID in the following places:
-- opening summary paragraph
-- Goals section.
-- Closing paragraph 
- All coding samples should mention QPID in the opening comment and in general when they mention AMQP specifically.

### PR DESCRIPTION
**Pull request by ghost**
Fixing the project configuration after its URL was changed and corresponding text changes

Signed-off-by: Dmitri Fedorov <dfedorov.solace@gmail.com>

Fixed #13

### CODE REVIEW

**Comment by mdspielman** [comment]
This looks great. The following item is still not addressed yet however:

* README quick links to tutorials need a link update to reflect final project naming.

I'd like to fix this prior to merging.

**Comment by ghost** [comment]
Yes, thank you for noticing, Mark, I missed that one.

**Comment by ghost** [comment]
See commit 5c9c0b23d0b0026d20996f7a189d9b0af933b3f6

**Comment by dfedorov-solace** [comment]
Fixes #13

**Pull request merged**
