### PR TITLE
Expanded build instructions

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Dmitri Fedorov <dfedorov.solace@gmail.com>

### CODE REVIEW

**Comment by ghost** [comment]
@jschabowsky Jonathan, check it out, is it want you meant me to add? If yes I'll do the same for JMS 2.0...

**Comment by jschabowsky** [comment]
Dmitri,

That looks good, you also need to edit the section “Building” and per Mark, have just Gradle for consistency. I think in the future we could maybe add back what you have, so keep it around.

Jonathan

**Comment by ghost** [comment]
@jschabowsky Jonathan, see 516b973783ae59b15b5f35055a1669adf168223d, is that was was meant?
Also I've talked to Mark about the pinetree and we agreed to replace it all with exceptions thrown.
I'll do the change in BasicReplier and propagate it throughout AMQP tutorials.

**Comment by ghost** [comment]
Sorry @jschabowsky Jonathan, missed one spot 76ed1d77eb56ef1a8ec530bdc7e521d6f22d0741

**Comment by ghost** [comment]
@jschabowsky @mdspielman all ready

**Comment by jschabowsky** [comment]
Looks good! I think we are good to merge and if we find something after that, we can always do a quick update.

**Comment by ghost** [comment]
Thank you Jonathan

**Pull request merged**
